### ISSUE TITLE
convertToCaffe ValueError: could not broadcast input array from shape (2048,1800) into shape (2048,2080)

### ISSUE THREAD

**Issue by SuperPengXue** [xiya888/lane_detect_convert#1]

**Comment by SuperPengXue** [comment]
> thank you for your great work!
> use convertToCaffe.py to convert culane_18.onnx
> I meet a error below
> converter_fn(net, node, graph, err)
> net.params[node_name][0].data[...] = W
> ValueError: could not broadcast input array from shape (2048,1800) into shape (2048, 2080)
> 
> Very confusing with"2080"
> set in the model.py
> self.cls = torch.nn.Sequential(
> torch.nn.Linear(1800, 2048),
> torch.nn.ReLU(),
> torch.nn.Linear(2048, self.total_dim),
> 
> do you know why? thanks

**Comment by xiya888** [comment]
hi, i haven't met this issue, you can check the parameter cls_dim in the convertToCaffe.py, is that the same?

**Comment by SuperPengXue** [comment]
thanks for your reply, I got it ,Problem is func cell() in pooling layer at my caffe

**Comment by dragonhaha** [comment]
Hello, I met the same problem. Can you help me?
